<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-POFN5K0" name="com.qa.opencart.tests.AccountsPageTest" tests="10" failures="1" timestamp="28 Aug 2021 12:07:37 GMT" time="20.906" errors="0">
  <testcase name="accPageTitleTest" time="0.019" classname="com.qa.opencart.tests.AccountsPageTest"/>
  <testcase name="accPageHeaderTest" time="0.074" classname="com.qa.opencart.tests.AccountsPageTest">
    <failure type="java.lang.AssertionError" message="expected [Your Store11] but found [Your Store]">
      <![CDATA[java.lang.AssertionError: expected [Your Store11] but found [Your Store]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.qa.opencart.tests.AccountsPageTest.accPageHeaderTest(AccountsPageTest.java:46)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- accPageHeaderTest -->
  <testcase name="accSectionsListTest" time="0.226" classname="com.qa.opencart.tests.AccountsPageTest"/>
  <testcase name="logoutLinkExistTest" time="0.139" classname="com.qa.opencart.tests.AccountsPageTest"/>
  <testcase name="searchTest" time="2.241" classname="com.qa.opencart.tests.AccountsPageTest"/>
  <testcase name="searchTest" time="2.167" classname="com.qa.opencart.tests.AccountsPageTest"/>
  <testcase name="searchTest" time="2.299" classname="com.qa.opencart.tests.AccountsPageTest"/>
  <testcase name="selectProductTest" time="4.515" classname="com.qa.opencart.tests.AccountsPageTest"/>
  <testcase name="selectProductTest" time="5.024" classname="com.qa.opencart.tests.AccountsPageTest"/>
  <testcase name="selectProductTest" time="4.202" classname="com.qa.opencart.tests.AccountsPageTest"/>
</testsuite> <!-- com.qa.opencart.tests.AccountsPageTest -->
